export default[
    {
    	id:1,
    	name:'亚里亚',
    	author:'佚名',
    	worksName:'绯弹的亚里亚',
    	pageviews:7666,
    	img:'./images/亚里亚1.jpg'
    },
    {
    	id:2,
    	name:'夏娜',
    	author:'伊东杂音',
    	worksName:'灼眼的夏娜',
    	pageviews:12333,
    	img:'./images/夏娜1.jpg'
    },
    {
    	id:3,
    	name:'凉宫春日',
    	author:'伊东杂音',
    	worksName:'凉宫春日的忧郁',
    	pageviews:10388,
    	img:'./images/凉宫春日1.jpg'
    },
    {
    	id:4,
    	name:'高坂桐乃',
    	author:'神崎广',
    	worksName:'我的妹妹不可能那么可爱',
    	pageviews:15699,
    	img:'./images/高坂桐乃1.jpg'
    },
    {
    	id:5,
    	name:'永见凉花',
    	author:'ぎん太郎',
    	worksName:'我喜欢的是小说里的你',
    	pageviews:8236,
    	img:'./images/永见凉花1.jpg'
    },
    {
    	id:6,
    	name:'月白瞳美',
    	author:'P.A.Works',
    	worksName:'来自多彩世界的明天',
    	pageviews:6367,
    	img:'./images/月白瞳美1.jpg'
    }
]
